
detector:
  det_config: "/mnt/data/chaoran/food_ai_main/ckpts/yolov7/yolov7-w6.yaml"
  det_checkpoint: "/mnt/data/chaoran/food_ai_main/ckpts/yolov7/yolov7-w6_best.pt"
  
segmentation:
  seg_checkpoint: "**"

depth:
  ckpt: "ckpt/cenet/lastest.pth"
  model: "cfnet"
  maxdisp: 192


retrieval:
  retrieval_checkpoint: "/mnt/data/chaoran/food_ai_main/ckpts/retrieval/checkpoint_deit_food500.pth.tar"
  input_shape: 256
  dim: 128
  batch_size: 256
  gallery_list: "gallery.txt"
  top_k: 5

