
detector:
  det_config: "ckpts/yolov7/yolov7-w6.yaml"
  det_checkpoint: "ckpts/yolov7/yolov7-w6.pt"
segmentation:
  seg_checkpoint: "ckpts/sam/sam_b.pt"

depth:
  ckpt: "ckpts/depth/finetuning_model"
  model: "cfnet"
  maxdisp: 192


retrieval:
  retrieval_checkpoint: "ckpts/retrieval/Food1k_deit_pre_arcface.pth.tar"
  input_shape: 256
  dim: 128
  batch_size: 256
  gallery_list: "gallery.txt"
  top_k: 10

